### ISSUE TITLE
Error occurs when Tag A is used in a guild where it isn't made.

### ISSUE THREAD

**Issue by ExceptionDev** [ExceptionDev/Rick#32]
### Error Executing Command || Command Name: Execute
**Error Reason:** Object reference not set to an instance of an object.  
**Target Site:** Void MoveNext()  
**Stack Trace:**
at Rick.Modules.TagModule.<ExecuteAsync>d__4.MoveNext() in G:\Github projects\Rick\Modules\TagModule.cs:line 66
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_1.<<BuildCommand>b__1>d.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__38.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__38.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Discord.Commands.CommandInfo.<ExecuteAsync>d__37.MoveNext()

**Comment by ExceptionDev** [comment]
Fixed it
Just need to add a check
